name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Win64
            target: Win64
            runs-on: windows-latest

          - name: MacOS
            target: MacOS
            runs-on: macos-latest

    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImpossibleLevelsGeode-${{ matrix.name }}
          path: ${{ steps.build.outputs.build-output }}
